name: Pyinstaller build windows exectuable

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8
    - name: Setup Project dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Build exectuable
      run: |
        ./pyinstaller-build.bat
      shell: bash
    - name: Publish to github
      run: |
        chmod +x upload-script.sh
        ./upload-script.sh 'dist/*'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
