name: Pyinstaller build windows exectuable

on: release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: 3.8
    - name: Setup Project dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Build windows exectuable
      run: |
        ./pyinstaller-build.bat
    - name: Publish to github
      run: |
        chmod +x upload-script.sh
        ./upload-script.sh 'dist/*.exe'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
